//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2019Course.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public int AuthorPass { get; set; }
        public string Journal { get; set; }
        public string Issue { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> CoauthorPass { get; set; }
        public int Year { get; set; }
    
        public virtual Leader Leader { get; set; }
        public virtual Work Work { get; set; }
    }
}
