//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2019Course.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Defence()
        {
            this.Voting = new HashSet<Voting>();
        }
    
        public int Number { get; set; }
        public int AuthorPass { get; set; }
        public int DisserId { get; set; }
        public System.DateTime Date { get; set; }
        public string Opponent { get; set; }
        public string Opponent2 { get; set; }
        public string Result { get; set; }
        public string City { get; set; }
        public string Organisation { get; set; }
        public string Building { get; set; }
        public string Auditory { get; set; }
    
        public virtual Disser Disser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voting> Voting { get; set; }
    }
}
