//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2019Course.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndPlan
    {
        public int Id { get; set; }
        public int AspirantId { get; set; }
        public string WorkName { get; set; }
        public int Size { get; set; }
        public System.DateTime DueDate { get; set; }
        public string DoneMarker { get; set; }
        public string Readiness { get; set; }
        public int Year { get; set; }
    
        public virtual Aspirant Aspirant { get; set; }
    }
}
