//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2019Course.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int DisserId { get; set; }
        public int AuthorPass { get; set; }
        public string ReviewAuthor { get; set; }
        public string Organisation { get; set; }
    
        public virtual Disser Disser { get; set; }
    }
}
