//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2019Course.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voting
    {
        public string VoteNumber { get; set; }
        public int Members { get; set; }
        public int Arrived { get; set; }
        public int Pro { get; set; }
        public int Contra { get; set; }
        public int Not_Voted { get; set; }
        public int DisserId { get; set; }
        public int AuthorPass { get; set; }
        public int DefenceId { get; set; }
    
        public virtual Defence Defence { get; set; }
    }
}
